database_path: "data_store/vector_db/faiss"

database_config:
  chunk_size: 1800
  separator: "\n"
  chunk_overlap: 360

pdf_path: "data_store/pdf"
word_path: "data_store/word"
csv_path: "data_store/csv"
excel_path: "data_store/excel"
